### ISSUE TITLE
Doesn't work on new update Qt6 running Sonoma 14.3

### ISSUE THREAD

**Issue by catydiaz4863** [realmayus/anki_forvo_dl#104]
Downloaded most recent version[Download Anki for macOS 12+ (Apple Silicon, 24.04 Qt6)](https://github.com/ankitects/anki/releases/download/24.04/anki-24.04-mac-apple-qt6.dmg)
I am running MacOS Sonoma 14.3

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.3-arm64-arm-64bit

When loading anki-forvo-dl - Forvo Pronunciation Downloader fully automatic:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/username/Library/Application Support/Anki2/addons21/858591644/__init__.py", line 14, in <module>
    from .src.About import About
  File "/Users/username/Library/Application Support/Anki2/addons21/858591644/src/About.py", line 1, in <module>
    from PyQt5.QtWidgets import QDialog, QLabel, QVBoxLayout
ModuleNotFoundError: No module named 'PyQt5'

**Comment by realmayus** [comment]
Fixed with #101
