### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bicolino34** [realmayus/anki_forvo_dl#22]
When I press "Forvo" button an error ocurrs

Debug info:
Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 8.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-03 18:25:37

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 36, in cmd
  File "aqt\webview.py", line 135, in _onCmd
  File "aqt\webview.py", line 580, in _onBridgeCmd
  File "aqt\editor.py", line 466, in onBridgeCmd
  File "C:\Users\OK\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 164, in on_editor_btn_click
    proceed(config_lang.value)
  File "C:\Users\OK\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 99, in proceed
    raise Exception()
Exception

**Comment by bicolino34** [comment]
I tried to add audio to other words, and it worked. I don't know why an error occurs only with the word "südöstlicher". Pronunciation for this word is available on Forvo.

**Comment by kaladin-syl** [comment]
Same issue except I'm suddenly getting this with every word. It was working fine 2 hours ago.

**Comment by o-se** [comment]
Hello @realmayus ,
I am receiving the exact same error message, with a slight difference,
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-06-27 18:47:03
File "aqt\editor.py", line 369, in checkFocus
File "C:\Users\Omar\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 206, in <lambda>
    shortcuts.append(("Ctrl+F", lambda: on_editor_btn_click(editor, False)))
  File "C:\Users\OK\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 164, in on_editor_btn_click
    proceed(config_lang.value)
  File "C:\Users\OK\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 99, in proceed
    raise Exception()
Exception

No word actually works. I tried to fully uninstall anki, restart my laptop, reinstall it. Didn’t work. I tried the VPN solution, didn’t work. I am on anki 2.1.40, thanks a lot if you ever have the time to take a look at it.

**Comment by realmayus** [comment]
Thanks for all the crashlogs, i'm sorry but I haven't had time to look into it. I'll publish a fix soon 👍

**Comment by realmayus** [comment]
@o-se I have a prototype ready. Could you please check if this fixed the issue for you?

**Please go to the addons manager and remove the old version first**

Then, you should be able to double-click the .ankiaddon file in this zip archive, and Anki should install it automatically.
[anki_forvo_dl.ankiaddon.zip](https://github.com/realmayus/anki_forvo_dl/files/6722381/anki_forvo_dl.ankiaddon.zip)
