### ISSUE TITLE
Caught exception

### ISSUE THREAD

**Issue by neoshamangames** [realmayus/anki_forvo_dl#32]
This is a fresh install, using Anki Version ⁨2.1.44 (b2b3275f)⁩
I just click the Forvo button and answer the questions and it produces this:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-15 14:31:22
Add-ons possibly involved: ⁨anki-forvo-dl  Forvo Pronunciation Downloader fully automatic⁩

Caught exception:
Traceback (most recent call last):
  File "/home/k/.local/share/Anki2/addons21/858591644/__init__.py", line 172, in handle_lang_select
    proceed(d.selected_lang)
  File "/home/k/.local/share/Anki2/addons21/858591644/__init__.py", line 99, in proceed
    raise Exception()
Exception

```

This is the deck I'm attempting to use the plugin with:
https://ankiweb.net/shared/info/638411848

**Comment by Xetile** [comment]
Same problem here.
