### ISSUE TITLE
Preferences dialog not opening

### ISSUE THREAD

**Issue by yaoberh** [realmayus/anki_forvo_dl#46]
After pressing the Tools->Preferences button this error appears:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.9.7 Qt 5.15.2 PyQt 5.15.4
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2021-09-30 21:41:54
Add-ons possibly involved: ⁨anki-forvo-dl - Forvo Pronunciation Downloader fully automatic⁩

Caught exception:
Traceback (most recent call last):
  File "/home/yannicko/.local/share/Anki2/addons21/858591644/__init__.py", line 226, in on_pref_btn_click
    config_manager = ConfigManager(config)
  File "/home/yannicko/.local/share/Anki2/addons21/858591644/src/ConfigManager.py", line 123, in __init__
    self.nt_selector.addItem(str(next(nt.name for nt in self.mw.col.models.all_names_and_ids() if nt.id == nt_id)), nt_id)
StopIteration

```

**Comment by realmayus** [comment]
Thanks for the report! I'll have a look.
