### ISSUE TITLE
it found the audo I need, but error pop up after I tried to check it.

### ISSUE THREAD

**Issue by cindynap** [realmayus/anki_forvo_dl#80]
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-08-30 08:03:47

Caught exception:
Traceback (most recent call last):
  File "C:\Users\-\AppData\Roaming\Anki2\addons21\858591644\src\AddSingle.py", line 58, in <lambda>
    btn_select.clicked.connect(lambda: select_pronunciation(pronunciation))
  File "C:\Users\-\AppData\Roaming\Anki2\addons21\858591644\src\AddSingle.py", line 113, in select_pronunciation
    pronunciation.download_pronunciation()
  File "C:\Users\-\AppData\Roaming\Anki2\addons21\858591644\src\Forvo.py", line 41, in download_pronunciation
    with open(dl_path, "wb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\-\\AppData\\Roaming\\Anki2\\addons21\\858591644\\temp\\pronunciation_fr_Comment réglez-vous?.ogg'

**Comment by realmayus** [comment]
Fixed by https://github.com/realmayus/anki_forvo_dl/commit/424db9ea5fe97c53b24769b31b9bd4dc90176154
