### ISSUE TITLE
ValueError: too many values to unpack (expected 1)

### ISSUE THREAD

**Issue by Expertium** [realmayus/anki_forvo_dl#90]
Debug info:
Anki 2.1.55 (6944210f) Python 3.9.7 Qt 6.3.2 PyQt 6.3.1
Platform: Windows-10-10.0.19044
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-11-29 00:51:41

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 553, in handler
  File "aqt.editor", line 586, in <lambda>
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 217, in <lambda>
    editor.saveNow(lambda: add_pronunciation(editor, mode))
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 130, in add_pronunciation
    results = forvo.get_pronunciations().pronunciations
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\src\Forvo.py", line 149, in get_pronunciations
    id_, = {
ValueError: too many values to unpack (expected 1)

**Comment by homocomputeris** [comment]
Request: `もしもし`
```
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-27 01:40:58
Reason: ⁨anki-forvo-dl - Forvo Pronunciation Downloader fully automatic⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 562, in handler
  File "aqt.editor", line 576, in <lambda>
  File "/Users/user/Library/Application Support/Anki2/addons21/858591644/__init__.py", line 217, in <lambda>
    editor.saveNow(lambda: add_pronunciation(editor, mode))
  File "/Users/user/Library/Application Support/Anki2/addons21/858591644/__init__.py", line 130, in add_pronunciation
    results = forvo.get_pronunciations().pronunciations
  File "/Users/user/Library/Application Support/Anki2/addons21/858591644/src/Forvo.py", line 149, in get_pronunciations
    id_, = {
ValueError: too many values to unpack (expected 1)
```

**Comment by swerage** [comment]
+1. Request: `弄り回す`

**Comment by OltiP2** [comment]
i also get a similar error when i try `満足`

**Comment by realmayus** [comment]
Fixed by https://github.com/realmayus/anki_forvo_dl/commit/3f1e40aab0bf950343e7ac0727d18587deb19876
